export const PURCHASING_TYPE_CASH = 'Kontan';
export const PURCHASING_TYPE_CREDIT = 'Kredit';

export const PURCHASING_PAYMENT_STATUS_PAID = 'Lunas';
export const PURCHASING_PAYMENT_STATUS_UNPAID = 'Belum Dibayar';
export const PURCHASING_PAYMENT_STATUS_OUTSTANDING = 'Belum Lunas';
export const PURCHASING_PAYMENT_STATUS_PROCESSING = 'Memproses Data';
export const PURCHASING_PAYMENT_STATUS_DRAFT = 'Draft';

export const PURCHASING_TYPE_OPTIONS = [
	{
		value: PURCHASING_TYPE_CASH,
		label: PURCHASING_TYPE_CASH,
	},
	{
		value: PURCHASING_TYPE_CREDIT,
		label: PURCHASING_TYPE_CREDIT,
	},
];

export const PURCHASING_PAYMENT_STATUS = [
	{
		value: PURCHASING_PAYMENT_STATUS_PAID,
		label: PURCHASING_PAYMENT_STATUS_PAID,
	},
	{
		value: PURCHASING_PAYMENT_STATUS_OUTSTANDING,
		label: PURCHASING_PAYMENT_STATUS_OUTSTANDING,
	},
	{
		value: PURCHASING_PAYMENT_STATUS_UNPAID,
		label: PURCHASING_PAYMENT_STATUS_UNPAID,
	},
	{
		value: PURCHASING_PAYMENT_STATUS_PROCESSING,
		label: PURCHASING_PAYMENT_STATUS_PROCESSING,
	},
	{
		value: PURCHASING_PAYMENT_STATUS_DRAFT,
		label: PURCHASING_PAYMENT_STATUS_DRAFT,
	},
];
